=== sing-group/WARCProcessor/config/schema/config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
Schema for WarcGenerator XML Configuration
@author Miguel Callon
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="configuration">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="numSites" minOccurs="1" maxOccurs="1">
	        <xs:complexType>
	          <xs:simpleContent>
	            <xs:extension base="xs:integer">
		          	<xs:attribute name="onlyActiveSites" type="xs:boolean" use="required" />
		            <xs:attribute name="downloadAgain" type="xs:boolean" use="required" />
	            </xs:extension>	
	          </xs:simpleContent>
	        </xs:complexType>
	      </xs:element>
	      <!-- SPAN/HAM Ratio -->      
	      <xs:element name="ratio" minOccurs="1" maxOccurs="1">
	        <xs:complexType>
	          <xs:sequence>
			      <xs:element name="percentageSpam" minOccurs="0" maxOccurs="1" />
			      <xs:element name="quantitySpam" minOccurs="0" maxOccurs="1" />
	          </xs:sequence>
	          <xs:attribute name="isPercentage" type="xs:boolean" use="required" />
	        </xs:complexType>
	      </xs:element>
	      <!-- Output folder -->
	      <xs:element name="corpusDirPath" type="xs:string" minOccurs="1" maxOccurs="1"/>
	      <!-- Output folder to save warc files with spam contents  -->
	      <xs:element name="spamDirName" type="xs:string" minOccurs="1" maxOccurs="1"/>
	      <!-- Output folder to save warc files with ham contents  -->
	      <xs:element name="hamDirName" type="xs:string" minOccurs="1" maxOccurs="1"/>
	      <!-- Output file where the urls crawled succesfully are stored -->
	      <xs:element name="domainsLabeledFileName" type="xs:string" minOccurs="1" maxOccurs="1"/>
	      <!-- Output file where the urls crawled without succesfully are stored -->
	      <xs:element name="domainsNotFoundFileName" type="xs:string" minOccurs="1" maxOccurs="1"/>
	      <!-- Remove old files from the output folders -->
	      <xs:element name="flushOutputDir" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
	      <!-- Depth of crawling for each url crawled -->
	      <xs:element name="maxDepthOfCrawling" type="xs:integer" minOccurs="1" maxOccurs="1"/>
	      <!-- Number of crawlers to scanner the urls -->
	      <xs:element name="numCrawlers" type="xs:integer" minOccurs="1" maxOccurs="1"/>
	      <!-- Folder to store temporary crawler data -->
	      <xs:element name="webCrawlerDirTmpStorePath" type="xs:string" minOccurs="1" maxOccurs="1"/>
	      <!-- Follow the link when it being a redirect -->
	      <xs:element name="followRedirect" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
	      
	      <!-- Datasource definitions -->
	      <xs:element name="dataSources" minOccurs="1" maxOccurs="1">
	        <xs:complexType>
		      <xs:sequence>
		      	 <xs:element name="dataSource" minOccurs="0" maxOccurs="unbounded">
			        <xs:complexType>
			          <xs:sequence>
			            <!-- This tag allow to add new parameters in a customized datasource -->
			            <xs:element name="customParams" 
			            	minOccurs="0" maxOccurs="1" />
			            <xs:element name="languages" 
			            	minOccurs="0" maxOccurs="1" >
			           		<xs:complexType>
			            		<xs:sequence>
			            			 <xs:element name="language" minOccurs="0" 
			            			 maxOccurs="unbounded">
			            			 	<xs:complexType>
								          <xs:simpleContent>
								            <xs:extension base="xs:string">
									          	<xs:attribute name="code" type="xs:string" use="required" />
								            </xs:extension>	
								          </xs:simpleContent>
								        </xs:complexType>
									</xs:element>
			             		</xs:sequence>
			             	</xs:complexType>
			            </xs:element>	
			            	
			            <!-- Input folder to get files with source urls -->
			            <xs:element name="srcDirPath" type="xs:string" minOccurs="1" maxOccurs="1" />
			            <!-- Fully qualified name of the class used for preprocesing source urls -->
			            <xs:element name="handler" type="xs:string" minOccurs="0" maxOccurs="1" />
			          </xs:sequence>
			          <!-- Name identifier -->
			          <xs:attribute name="name" type="xs:string" use="required" />
			          <!-- Fully qualified name of the class that implements this datasource -->
			          <xs:attribute name="type" type="xs:string" use="required" />
			          <!-- Max number of url to read from this datasource -->
			          <xs:attribute name="maxElements" type="xs:integer" use="optional" />
			          <!-- Used for specify if all urls from this datasource are spam or ham -->
			          <xs:attribute name="isSpam" type="xs:boolean" use="optional" />
			        </xs:complexType>
			      </xs:element>
		      </xs:sequence>
		    </xs:complexType>
		  </xs:element>
	    </xs:sequence>
	    <!-- Tag to specify an schema -->
	    <xs:attribute name="noNamespaceSchemaLocation" type="xs:string" use="optional" />
	  </xs:complexType>
	</xs:element>
</xs:schema>

=== sing-group/WARCProcessor/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd"
>
	 <!-- Corpus configuration  -->
	 <corpusDirPath>.\\out</corpusDirPath>
	 <spamDirName>_spam_</spamDirName>
	 <hamDirName>_ham_</hamDirName>
	 <domainsLabeledFileName>domains.labelled</domainsLabeledFileName>
	 <domainsNotFoundFileName>domains.notFound</domainsNotFoundFileName>
	 
	 <!--  Others -->
	 <flushOutputDir>false</flushOutputDir>
	 <maxDepthOfCrawling>0</maxDepthOfCrawling>
	 <numCrawlers>2</numCrawlers>
	 <webCrawlerDirTmpStorePath>.</webCrawlerDirTmpStorePath>
	 
	 <!--  Data sources -->
	 <dataSources>
	 	 <dataSource name="CorpusDS" 
	 	 	class="com.warcgenerator.datasources.CorpusDS" 
	 		maxElements="10" >
	 		<customParams>
	 			<urlTag>WARC-Target-URI</urlTag>
	 			<spamDir>_spam_</spamDir>
	 			<hamDir>_ham_</hamDir>
	 		</customParams>
	 		<srcDirPath>.\\in\\corpus</srcDirPath>
	 		<handler>com.warcgenerator.datasources.handler.CorpusDSHandler</handler>
	 	</dataSource>
	 	<dataSource name="ArffDS"
	 		class="com.warcgenerator.datasources.ArffDS"
	 		maxElements="10" >
	 		<customParams>
	 			<spamTag>LABEL</spamTag>
	 			<urlTag>URL</urlTag>
	 		</customParams>
	 		<srcDirPath>.\\in\\arff</srcDirPath>
	 		<handler>com.warcgenerator.datasources.handler.ArffDSHandler</handler>
	 	</dataSource>
	 	<dataSource name="WhitelistDS" 
	 		class="com.warcgenerator.datasources.FileDS">
	 		<srcDirPath>.\\in\\plain\whitelists</srcDirPath>
	 		<handler>com.warcgenerator.datasources.handler.FileDSHandler</handler>
	 	</dataSource>
	 	<dataSource name="BlacklistDS" 
	 		class="com.warcgenerator.datasources.FileDS"
	 		isSpam="true" >
	 		<srcDirPath>.\\in\\plain\blacklists</srcDirPath>
	 		<handler>com.warcgenerator.datasources.handler.FileDSHandler</handler>
	 	</dataSource>
	 	<dataSource name="CSVDS" 
	 		class="com.warcgenerator.datasources.CSVDS">
	 		<customParams>
	 			<urlColNum>0</urlColNum>
	 		</customParams>
	 		<srcDirPath>.\\in\\csv</srcDirPath>
	 		<handler>com.warcgenerator.datasources.handler.CSVDSHandler</handler>
	 	</dataSource>
	 </dataSources>
</configuration>
